In [ ]:
#multiple heterogeneous pararllel models are built >>>heterogenous ensembles
#majority voting classifier

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings("ignore")

In [ ]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
x,y=make_classification(n_samples=100,n_features=20,n_classes=2,random_state=1)

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [ ]:
x_train

array([[ 0.60640394,  0.68064537,  1.02124813, ...,  1.03703898,
        -0.83001099, -0.03599018],
       [-0.5301198 ,  1.04541272,  0.71829074, ..., -0.06962454,
         0.16056499, -2.277298  ],
       [-2.30803851, -1.42368943,  1.14256392, ..., -0.24701649,
        -0.37911961,  0.27610275],
       ...,
       [ 1.10861676,  0.651448  ,  0.78046993, ..., -0.23787527,
         0.72555052, -0.09243232],
       [ 0.14164054, -1.27406042,  1.71066184, ...,  0.98635218,
        -0.59566788,  0.66168108],
       [-2.79144404,  1.06080576, -2.26261533, ..., -0.48272686,
         0.45271362, -0.03848246]])

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB

In [ ]:
model1=LogisticRegression()
model2=DecisionTreeClassifier()
model3=SVC()
model4=GaussianNB()

In [ ]:
#for ensembles
from sklearn.ensemble import VotingClassifier
ensemble_clf=VotingClassifier(estimators=[('logistic_reg',model1),('Decision_tree',model2),('svm',model3),("gaussian",model4)],voting="hard")

In [ ]:
ensemble_clf

VotingClassifier(estimators=[('logistic_reg', LogisticRegression()),
                             ('Decision_tree', DecisionTreeClassifier()),
                             ('svm', SVC()), ('gaussian', GaussianNB())])

In [ ]:
ensemble_clf.fit(x_train,y_train)

VotingClassifier(estimators=[('logistic_reg', LogisticRegression()),
                             ('Decision_tree', DecisionTreeClassifier()),
                             ('svm', SVC()), ('gaussian', GaussianNB())])

In [ ]:
y_pred=ensemble_clf.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9

In [ ]:
#BAGGING REGRESSOR OR HARD VOTING REGRESSOR
from sklearn.datasets import make_regression
x,y=make_regression(n_samples=1000,n_features=20,noise=0.1,random_state=1)
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [ ]:
x_train

array([[-0.18408271, -1.01367978, -1.13276785, ..., -0.14717707,
         1.22773598,  0.00770072],
       [ 0.11274315,  0.32037801,  0.85824733, ...,  0.05259282,
        -1.12052172,  0.52393304],
       [ 0.09337653,  0.02843461,  0.74712724, ...,  0.86877214,
        -0.30268316,  0.53358243],
       ...,
       [ 0.07395844, -0.869738  , -0.91510703, ...,  1.48118549,
        -0.31794095,  1.4690611 ],
       [-0.96561276, -0.27907264,  0.41345967, ..., -0.44097524,
        -0.10279822, -0.89793731],
       [ 0.12646586,  0.58955817,  0.62266974, ...,  0.0159744 ,
         1.09781828, -0.82888194]])

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR

In [ ]:
l_r=LinearRegression()
Dtr=DecisionTreeRegressor()
svr=SVR(kernel="linear")

In [ ]:
from sklearn.ensemble import VotingRegressor
ensemble_reg=VotingRegressor(estimators=[("linear_reg",l_r),('Decision_tree',Dtr),('SVR',svr)])

In [ ]:
ensemble_reg

VotingRegressor(estimators=[('linear_reg', LinearRegression()),
                            ('Decision_tree', DecisionTreeRegressor()),
                            ('SVR', SVR(kernel='linear'))])

In [ ]:
ensemble_reg.fit(x_train,y_train)


VotingRegressor(estimators=[('linear_reg', LinearRegression()),
                            ('Decision_tree', DecisionTreeRegressor()),
                            ('SVR', SVR(kernel='linear'))])

In [ ]:
y_pred=ensemble_reg.predict(x_test) #average of all the prediction will be the final prediction

In [ ]:
y_pred

array([-1.82330465e+02,  2.92732055e+01, -1.78097171e+02,  1.04566503e+02,
        8.41897841e+01, -1.57287589e+02, -1.57358857e+02, -8.44351073e+01,
        5.01162766e+01, -9.71683663e+01,  2.51656577e+02,  4.86147976e+01,
        6.91964459e+01, -8.57479733e+01, -2.89358838e+02, -2.28034930e+02,
       -1.48162334e+02, -3.29721742e+01, -1.71998002e+02,  1.67880196e+02,
        9.56650335e+01, -1.75109113e+01, -6.52998890e+01, -1.14683628e+02,
       -3.08815510e+01,  8.22396237e+01,  1.02888265e+02, -5.51894429e+01,
        2.31723184e+02, -9.05067438e-01,  2.98230268e+02,  2.77635100e+02,
       -9.36020431e+01, -3.27380608e+00,  1.66522002e+01,  4.06313498e+01,
       -1.29841394e+02,  3.35057953e+02, -1.09712937e+02,  1.74476442e+01,
        9.98000442e+01, -7.30588634e+01, -1.02601981e+02, -6.30684221e+01,
        1.49011620e+02, -2.17062019e+01,  8.16496283e+01,  1.13432680e+02,
       -1.30342494e+02,  2.14578210e+02, -2.54733268e+02, -1.98597851e+02,
       -6.21183365e+01,  

In [ ]:
from sklearn.metrics import r2_score,mean_squared_error

In [ ]:
r2_score(y_test,y_pred)

0.9437155677301928

In [ ]:
mean_squared_error(y_test,y_pred)

1325.278418367085