In [ ]:
#Multiple model training,Pipeline and column Transformer

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings("ignore")

In [ ]:
df=sns.load_dataset("tips")

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   total_bill  244 non-null    float64 
 1   tip         244 non-null    float64 
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64   
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB


In [ ]:
#predict what is the time?  if any one is visting ...is it lunch or dinner? time is the target varible
df.time.unique()

['Dinner', 'Lunch']
Categories (2, object): ['Lunch', 'Dinner']

In [ ]:
#EDA
#data preparation >>encoding ,missing value treatement,scaling
#now we wiil automate this data preparartion using pipeline and column transfer

In [ ]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [ ]:
#since time is nominal variable, the we will use label encoder
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
df["time"]=encoder.fit_transform(df["time"])

In [ ]:
df["time"]

0      0
1      0
2      0
3      0
4      0
      ..
239    0
240    0
241    0
242    0
243    0
Name: time, Length: 244, dtype: int64

In [ ]:
df["time"].unique() #lunch>>0,dinner>>1

array([0, 1])

In [ ]:
df

total_bill   tip     sex smoker   day  time  size
0         16.99  1.01  Female     No   Sun     0     2
1         10.34  1.66    Male     No   Sun     0     3
2         21.01  3.50    Male     No   Sun     0     3
3         23.68  3.31    Male     No   Sun     0     2
4         24.59  3.61  Female     No   Sun     0     4
..          ...   ...     ...    ...   ...   ...   ...
239       29.03  5.92    Male     No   Sat     0     3
240       27.18  2.00  Female    Yes   Sat     0     2
241       22.67  2.00    Male    Yes   Sat     0     2
242       17.82  1.75    Male     No   Sat     0     2
243       18.78  3.00  Female     No  Thur     0     2

[244 rows x 7 columns]

In [ ]:
x=df.drop("time",axis=1)
y=df["time"]
x

total_bill   tip     sex smoker   day  size
0         16.99  1.01  Female     No   Sun     2
1         10.34  1.66    Male     No   Sun     3
2         21.01  3.50    Male     No   Sun     3
3         23.68  3.31    Male     No   Sun     2
4         24.59  3.61  Female     No   Sun     4
..          ...   ...     ...    ...   ...   ...
239       29.03  5.92    Male     No   Sat     3
240       27.18  2.00  Female    Yes   Sat     2
241       22.67  2.00    Male    Yes   Sat     2
242       17.82  1.75    Male     No   Sat     2
243       18.78  3.00  Female     No  Thur     2

[244 rows x 6 columns]

In [ ]:
y

0      0
1      0
2      0
3      0
4      0
      ..
239    0
240    0
241    0
242    0
243    0
Name: time, Length: 244, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [ ]:
x_train

tip     sex smoker   day  time  size
0    1.01  Female     No   Sun     0     2
154  2.00    Male     No   Sun     0     4
167  4.50    Male     No   Sun     0     4
110  3.00    Male     No   Sat     0     2
225  2.50  Female    Yes   Fri     1     2
..    ...     ...    ...   ...   ...   ...
137  2.00  Female     No  Thur     1     2
72   3.14  Female    Yes   Sat     0     2
140  3.50  Female     No  Thur     1     2
235  1.25    Male     No   Sat     0     2
37   3.07  Female     No   Sat     0     3

[195 rows x 6 columns]

In [ ]:
#handling the missing value
#data encoding
#featuer scaling

from sklearn.impute import SimpleImputer #for missing value treatment
from sklearn.preprocessing import OneHotEncoder #for encoding
from sklearn.preprocessing import StandardScaler  #for scaling


from sklearn.pipeline import Pipeline # give the sequence of data transformer
from sklearn.compose import ColumnTransformer #grops all the pipeline steps for each of the columns

In [ ]:
df.sample(1) #return the random sample

total_bill   tip   sex smoker  day  time  size
235       10.07  1.25  Male     No  Sat     0     2

In [ ]:
categorical_cols=["sex","smoker","day"]
numerical_cols=["total_bill","tip","size"]

In [ ]:
#feature engennering automation using pipeline and column tranformer
#numerical pipeline
num_pipeline=Pipeline(steps=[("imputation",SimpleImputer(strategy="median")),("scaling",StandardScaler())])
#categorical pipleine
cat_pipeline=Pipeline(steps=[("imputation",SimpleImputer(strategy="most_frequent")),("encoding",OneHotEncoder())])

In [ ]:
preprocessor=ColumnTransformer([("num_pipeline",num_pipeline,numerical_cols),("cat_pipeline",cat_pipeline,categorical_cols)])

In [ ]:
x_train=preprocessor.fit_transform(x_train)
x_test=preprocessor.transform(x_test)

AttributeError: 'numpy.ndarray' object has no attribute 'fit'

In [ ]:
x_train

array([[-0.28611937, -1.47443803, -0.57766863, ...,  0.        ,
         1.        ,  0.        ],
       [ 0.02695905, -0.71612531,  1.47042924, ...,  0.        ,
         1.        ,  0.        ],
       [ 1.3716196 ,  1.19880579,  1.47042924, ...,  0.        ,
         1.        ,  0.        ],
       ...,
       [-0.23206267,  0.43283335, -0.57766863, ...,  0.        ,
         0.        ,  1.        ],
       [-1.06543688, -1.29060464, -0.57766863, ...,  1.        ,
         0.        ,  0.        ],
       [-0.29287646,  0.1034652 ,  0.44638031, ...,  1.        ,
         0.        ,  0.        ]])

In [ ]:
x_test

array([[-1.85376383, -1.48209775, -1.60171757,  1.        ,  0.        ,
         0.        ,  1.        ,  0.        ,  1.        ,  0.        ,
         0.        ],
       [-0.08453291,  0.04984713, -0.57766863,  1.        ,  0.        ,
         1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         1.        ],
       [ 0.79501474,  0.36389583,  0.44638031,  0.        ,  1.        ,
         0.        ,  1.        ,  0.        ,  1.        ,  0.        ,
         0.        ],
       [-0.59356688, -0.33313909, -0.57766863,  0.        ,  1.        ,
         1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         1.        ],
       [ 0.18349826,  0.04984713, -0.57766863,  0.        ,  1.        ,
         1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         1.        ],
       [-1.32783714, -1.14506988, -0.57766863,  0.        ,  1.        ,
         0.        ,  1.        ,  0.        ,  1.        ,  0.        ,
         0.   

In [ ]:
#now data is ready and you want to build the multiple models
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

In [ ]:
models={"support vector classifier":SVC(),
        "Decision tree":DecisionTreeClassifier(),
        "Logistic Regression":LogisticRegression(),
        "RandomForest":RandomForestClassifier()}
models

{'support vector classifier': SVC(),
 'Decision tree': DecisionTreeClassifier(),
 'Logistic Regression': LogisticRegression(),
 'RandomForest': RandomForestClassifier()}

In [ ]:
from sklearn.metrics import accuracy_score

def model_train_eval(x_train,x_test,y_train,y_test,models):
  evaluation={}
  for i in range(len(models)):
    model=list(models.values())[i]
    model.fit(x_train,y_train)
    y_pred=model.predict(x_test)
    model_score=accuracy_score(y_test,y_pred)
    evaluation[list(models.keys())[i]]=model_score
  return evaluation

In [ ]:
model_train_eval(x_train,x_test,y_train,y_test,models)

{'support vector classifier': 0.9183673469387755,
 'Decision tree': 0.8979591836734694,
 'Logistic Regression': 0.9183673469387755,
 'RandomForest': 0.8979591836734694}

In [ ]:
#RANDOM FOREST
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()
rf


RandomForestClassifier()

In [ ]:
x_train,x_test

(array([[-0.28611937, -1.47443803, -0.57766863, ...,  0.        ,
          1.        ,  0.        ],
        [ 0.02695905, -0.71612531,  1.47042924, ...,  0.        ,
          1.        ,  0.        ],
        [ 1.3716196 ,  1.19880579,  1.47042924, ...,  0.        ,
          1.        ,  0.        ],
        ...,
        [-0.23206267,  0.43283335, -0.57766863, ...,  0.        ,
          0.        ,  1.        ],
        [-1.06543688, -1.29060464, -0.57766863, ...,  1.        ,
          0.        ,  0.        ],
        [-0.29287646,  0.1034652 ,  0.44638031, ...,  1.        ,
          0.        ,  0.        ]]),
 array([[-1.85376383, -1.48209775, -1.60171757,  1.        ,  0.        ,
          0.        ,  1.        ,  0.        ,  1.        ,  0.        ,
          0.        ],
        [-0.08453291,  0.04984713, -0.57766863,  1.        ,  0.        ,
          1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          1.        ],
        [ 0.79501474,  0.363895

In [ ]:
from sklearn.model_selection import RandomizedSearchCV
params={'max_depth':[1,2,3,4,5,10,None],'n_estimators':[30,40,50,100,200,300],
        "criterion":['gini','entropy']}

In [ ]:
clf=RandomizedSearchCV(rf,param_distributions=params,cv=5,verbose=3,scoring="accuracy",n_iter=10)
clf

RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(),
                   param_distributions={'criterion': ['gini', 'entropy'],
                                        'max_depth': [1, 2, 3, 4, 5, 10, None],
                                        'n_estimators': [30, 40, 50, 100, 200,
                                                         300]},
                   scoring='accuracy', verbose=3)

In [ ]:
clf.fit(x_train,y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits
[CV 1/5] END criterion=entropy, max_depth=2, n_estimators=50;, score=0.923 total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=2, n_estimators=50;, score=0.974 total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=2, n_estimators=50;, score=1.000 total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=2, n_estimators=50;, score=1.000 total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=2, n_estimators=50;, score=1.000 total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=1, n_estimators=100;, score=0.923 total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=1, n_estimators=100;, score=0.897 total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=1, n_estimators=100;, score=1.000 total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=1, n_estimators=100;, score=1.000 total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=1, n_estimators=100;, score=1.000 total time=   0.1s
[CV 1/5] 

RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(),
                   param_distributions={'criterion': ['gini', 'entropy'],
                                        'max_depth': [1, 2, 3, 4, 5, 10, None],
                                        'n_estimators': [30, 40, 50, 100, 200,
                                                         300]},
                   scoring='accuracy', verbose=3)

In [ ]:
clf.best_params_

{'n_estimators': 50, 'max_depth': 2, 'criterion': 'entropy'}

In [ ]:
clf.best_score_

np.float64(0.9794871794871796)

In [ ]:
y_pred=clf.best_estimator_.predict(x_test)

In [ ]:
accuracy_score(y_test,y_pred)

0.9183673469387755